Repository FE-MWM/WanderGuide, pull requests merged in 2024-05, with the labels that each got.

#17 [13] feat : import React from "react" 사용 안하도록 설정
  .eslintrc.json
Labels: 개발환경 셋팅

#15 [09] feat: 레이아웃 작업
  public/background.js
  public/images/add-button.svg
  public/images/calendar.svg
  public/images/logo.svg
  public/images/notification.svg
  public/images/refresh.svg
  public/images/settings.svg
  public/images/user.svg
  public/images/wander-guide.svg
  public/images/write.svg
  public/manifest.json
  src/App.css
  src/App.tsx
  src/components/AccommodationSection/Accommodation.tsx
  src/components/ActivitySection/Activity.tsx
  src/components/Body.tsx
  src/components/BookDashboard.tsx
  src/components/CurrentTimeSection/CurrentTime.tsx
  src/components/ExchangeRateSection/ExchangeRate.tsx
  src/components/FlightPlansSection/FlightPlans.tsx
  src/components/Header.tsx
  src/components/MainDashboard.tsx
  src/components/Navbar.tsx
  src/components/Tab.tsx
  src/components/TravelItinerarySection/TravelItinerary.tsx
  src/components/Weather/Weather.tsx
  src/index.css
  src/index.tsx
  src/page/Home.tsx
  src/page/NotFound.tsx
Labels: UI 구현

#23 [13] feat : 안쓰는 변수의 경우 에러처리에서 경고처리로 변경
  .eslintrc.json
Labels: 개발환경 셋팅

#26 [13] feat: tailwind 프리티어 추가
  .prettierrc.json
  package-lock.json
  package.json
Labels: 개발환경 셋팅

#28 [27] feat: 데이터가 없을경우 여행지 추가해주세요 공통컴포넌트 분리
  public/images/plane-black.svg
  public/images/plane-blue.svg
  src/components/common/NoSettingData.tsx
  tailwind.config.js
Labels: UI 구현

#29 [10] feat: 날씨 UI 구현
  .prettierrc.json
  package-lock.json
  package.json
  public/images/location.svg
  src/Util/dateFormatter.ts
  src/api/weather.ts
  src/components/AccommodationSection/Accommodation.tsx
  src/components/ActivitySection/Activity.tsx
  src/components/CurrentTimeSection/CurrentTime.tsx
  src/components/ExchangeRateSection/ExchangeRate.tsx
  src/components/FlightPlansSection/FlightPlans.tsx
  src/components/MainDashboard.tsx
  src/components/Navbar.tsx
  src/components/TravelItinerarySection/TravelItinerary.tsx
  src/components/Weather/Weather.tsx
  src/components/Weather/WeatherList.tsx
  src/components/common/IsLoading.tsx
  src/page/Home.tsx
Labels: UI 구현, 기능 구현

#25 [08] feat: 공통 모달 컴포넌트 구현
  src/App.tsx
  src/components/AddTravelDestination.tsx
  src/components/Navbar.tsx
  src/components/common/Modal.tsx
  src/context/ModalContext.tsx
Labels: UI 구현

#36 [32] feat : 예약 탭의 숙소, 액티비티 투어 관련 UI 구현
  public/images/baggage.svg
  src/components/BookDashboard.tsx
  src/components/BookingSection/AccommodationList.tsx
  src/components/BookingSection/BookItem.tsx
  src/components/BookingSection/TourList.tsx
  src/components/Tab.tsx
  tailwind.config.js
Labels: UI 구현

#38 [37] feat : 여행지 추가 후 여행지 목록 리스트 UI 레이아웃
  src/components/Navbar.tsx
  src/page/Home.tsx
Labels: UI 구현

#40 [39] feat: 메인보드 숙소 , 액티비티/투어 임시데이터 ui 작업
  public/images/arrow-right.svg
  src/components/AccommodationSection/Accommodation.tsx
  src/components/ActivitySection/Activity.tsx
  src/components/ExchangeRateSection/ExchangeRate.tsx
  src/components/FlightPlansSection/FlightPlans.tsx
  src/components/MainDashboard.tsx
  src/components/Weather/WeatherList.tsx
  src/page/Home.tsx
Labels: UI 구현

#42 [41] feat: 비행기 UI 구현
  src/components/FlightPlansSection/FlightList.tsx
  src/components/FlightPlansSection/FlightPlans.tsx
  src/index.css
  tailwind.config.js
Labels: UI 구현

#45 [44] feat: tab 상태값 context로 생성 후, 변경, 더보기 클릭시 탭 이동하도록 수정
  src/components/AccommodationSection/Accommodation.tsx
  src/components/ActivitySection/Activity.tsx
  src/components/Body.tsx
  src/components/Weather/WeatherList.tsx
  src/context/TabContext.tsx
  src/page/Home.tsx
Labels: 기능 구현

#53 [34] feat: 여행지 추가 기능 작업
  package-lock.json
  package.json
  src/components/AddTravelDestination.tsx
  src/components/Navbar.tsx
  src/components/common/Modal.tsx
  src/context/ModalContext.tsx
  src/context/selectBox/SelectInput.tsx
  src/indexeddb/indexedDB.ts
  src/page/Home.tsx
  src/provider/AddTravelDestinationProvider.tsx
Labels: UI 구현, 기능 구현

#59 [57] feat : recoil 셋팅 및 테스트
  .eslintrc.json
  package-lock.json
  package.json
  src/App.tsx
  src/components/AddTravelDestination.tsx
  src/index.tsx
  src/indexeddb/indexedDB.ts
  src/page/Home.tsx
  src/provider/AddTravelDestinationProvider.tsx
  src/store/destinationAtoms.tsx
Labels: 개발환경 셋팅

#73 [72] fix : 비행기 ui 깨짐 오류 수정
  src/components/FlightPlansSection/FlightPlans.tsx
Labels: UI 구현

#74 [57] feat: recoil & IndexedDB 데이터 구조 설계
  src/components/Header.tsx
  src/components/Navbar.tsx
  src/components/TravelItinerarySection/TravelItinerary.tsx
  src/indexeddb/indexedDB.ts
  src/page/Home.tsx
  src/provider/AddTravelDestinationProvider.tsx
  src/store/destinationAtom.ts
  src/store/destinationAtoms.tsx
  src/store/planListAtom.ts
Labels: 개발환경 셋팅, 기능 구현

#75 fix: planInfo 오류 수정
  src/components/TravelItinerarySection/TravelItinerary.tsx
Labels: 버그

#78 fix: indexedDB 데이터 없을때 빈 배열로 저장되는 이슈 수정
  src/page/Home.tsx
Labels: 버그

#79 [76] feat : 데이터가 없는 경우 경우의 수 추가
  src/components/AccommodationSection/Accommodation.tsx
  src/components/ActivitySection/Activity.tsx
  src/components/AddTravelDestination.tsx
  src/components/Header.tsx
  src/components/Navbar.tsx
  src/components/TravelItinerarySection/TravelItinerary.tsx
  src/components/Weather/Weather.tsx
  src/provider/AddTravelDestinationProvider.tsx
  src/store/destinationAtom.ts
Labels: UI 구현

#81 fix: D-day영역 데이터 동기화 안되는 부분 수정
  src/provider/AddTravelDestinationProvider.tsx
Labels: 버그

#83 [80] feat : 날씨 데이터 api 수정
  src/components/Weather/WeatherList.tsx
  src/store/destinationAtom.ts
Labels: 기능 구현

#90 [55] feat: 현재 시각 부분 UI & 기능 구현
  package-lock.json
  package.json
  src/api/country.ts
  src/components/CountriesSelectBox.tsx
  src/components/CurrentTimeSection/CurrentTime.tsx
  src/hook/useCountries.ts
  src/provider/AddTravelDestinationProvider.tsx
  src/store/destinationAtom.ts
  src/store/initAtom.ts
Labels: UI 구현, 기능 구현

#91 fix: 에러 수정
  src/components/CountriesSelectBox.tsx
  src/hook/useCountries.ts
Labels: 버그

#93 [54] fix: body 영역에 D-day 구현 및 현재 시각 부분 수정
  src/components/CurrentTimeSection/CurrentTime.tsx
  src/components/TravelItinerarySection/TravelItinerary.tsx
Labels: UI 구현, 기능 구현

#98 [94] feat: 액티비티/투어 기능 구현
  package-lock.json
  package.json
  src/components/ActivitySection/Activity.tsx
  src/components/ActivitySection/ActivityModal.tsx
  src/components/BookDashboard.tsx
  src/components/BookingSection/ActivityItem.tsx
  src/components/BookingSection/ActivityList.tsx
  src/components/BookingSection/BookItem.tsx
  src/components/BookingSection/TourList.tsx
  src/store/destinationAtom.ts
Labels: UI 구현, 기능 구현

#100 [84] feat : 비행기 UI CRUD 작업
  public/images/delete.svg
  src/Util/calcFlight.ts
  src/Util/dateFormatter.ts
  src/components/FlightPlansSection/AddFlight.tsx
  src/components/FlightPlansSection/AddFlightItem.tsx
  src/components/FlightPlansSection/FlightList.tsx
  src/components/FlightPlansSection/FlightPlans.tsx
  src/components/Weather/WeatherList.tsx
  src/provider/AddFlightPlanProvider.tsx
  src/store/destinationAtom.ts
  src/store/initAtom.ts
Labels: UI 구현, 기능 구현

#102 [99] fix: 처음 여행지 등록시 recoil에 id 못찾는 오류 수정
  src/api/exchange.ts
  src/components/BookingSection/AccommodationList.tsx
  src/components/FlightPlansSection/FlightList.tsx
  src/indexeddb/indexedDB.ts
  src/provider/AddTravelDestinationProvider.tsx
Labels: 버그

#109 [101] feat : 숙소, 액티비티 UI 수정, 기능 수정
  src/components/AccommodationSection/Accommodation.tsx
  src/components/ActivitySection/Activity.tsx
  src/components/AddTravelDestination.tsx
  src/components/BookingSection/AccoBookItem.tsx
  src/components/BookingSection/AccommodationList.tsx
  src/components/BookingSection/ActivityItem.tsx
  src/components/BookingSection/ActivityList.tsx
  src/components/CurrentTimeSection/CurrentTime.tsx
  src/components/FlightPlansSection/FlightPlans.tsx
  src/components/TravelItinerarySection/TravelItinerary.tsx
  src/components/common/Modal.tsx
  src/context/selectBox/SelectList.tsx
  src/context/selectBox/SlectItem.tsx
Labels: UI 구현, 기능 구현

#118 [111] feat: 환율, 시간 로딩 스피너 추가 및 유틸함수분리
  src/Util/dateFormatter.ts
  src/components/CurrentTimeSection/CurrentTime.tsx
  src/components/ExchangeRateSection/ExchangeRate.tsx
  src/hook/useGetExchangeRate.ts
Labels: 기능 구현

#119 [114] feat: 여행지 삭제 기능 구현
  src/components/Navbar.tsx
  src/indexeddb/indexedDB.ts
  src/provider/AddTravelDestinationProvider.tsx
Labels: UI 구현, 기능 구현
